name: Erstelle Release und weise Artefakte zu

on:
  push:
    tags:
      - 'v*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version:  ${{ steps.setup.outputs.version }}
      docker_tag:  ${{ steps.setup.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        id: setup
        run: |
          if [ "${{inputs.tag}}" == "" ]; then
          COMMIT=${GITHUB_SHA::7}
          echo "docker_tag=$COMMIT" >> $GITHUB_OUTPUT
          else 
          echo "docker_tag=${{inputs.tag}}" >> $GITHUB_OUTPUT
          fi
          version=$(echo "${{github.ref}}" | sed 's#refs/tags/##')
          echo "version=$version" >> $GITHUB_OUTPUT
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
        with:
          tag: ${{ needs.setup.outputs.version }}
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Erstelle Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: Erstelle Release
          draft: false
          prerelease: false

      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: ./

      - name: Artefakte hochladen
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./wait-for-it
          asset_name: wait-for-it
          asset_content_type: application/octet-stream